data_url : "./data"

type_model : "Lstm_Embd" # use "Rnn" or "Rnn_Embd" or "Lstm" or "Lstm_Embd"
learning_rate : 0.0001
batch_size : 512
shuffle: 1 # sample datasets become random
epochs : 2
type_device : CPU

# Structural Models

n_neurons_embedding: 256
n_neurons_lstm: 512
n_neurons_timedistributed: 1024

