data_url : "./data"

type_model : "Lstm_Embd_20000" # use "Rnn" or "Rnn_Embd" or "Lstm" or "Lstm_Embd"
learning_rate : 0.0001
batch_size : 128
shuffle: 1 # sample datasets become random
epochs : 15
type_device : GPU

# Structural Models

n_neurons_embedding: 25
n_neurons_lstm: 512
n_neurons_timedistributed: 1024

